# Generated by Django 5.0.1 on 2024-01-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Enable', 'enable'), ('Disable', 'disable')], max_length=255)),
                ('amount', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
